export const navbarLinks = [
    {
        id: "about",
        title: "About Us",
    },
    {
        id: "services",
        title: "Services",
    },
    {
        id: "prices",
        title: "Prices",
    },
    {
        id: "gallery",
        title: "Gallery",
    },
    {
        id: "contact",
        title: "Contact Us",
    },
];

export const heroSectionCards = [
    {
        id: 1,
        heading: "Bathroom Renovations",
        btnText: "Get Started",
        imgUrl: "/assets/heroSection/hero-bathroom.png",
        skeletonImgUrl: "/assets/heroSection/skeleton/hero-skeleton-bathroom.png",
    },
    {
        id: 2,
        heading: "Kitchen Transformations",
        btnText: "Get Started",
        imgUrl: "/assets/heroSection/hero-kitchen.png",
        skeletonImgUrl: "/assets/heroSection/skeleton/hero-skeleton-kitchen.png",
    },
    {
        id: 3,
        heading: "Basement Renovation",
        btnText: "Get Started",
        imgUrl: "/assets/heroSection/hero-basement.png",
        skeletonImgUrl: "/assets/heroSection/skeleton/hero-skeleton-basement.png",
    },
];

export const servicesSectionCards = [
    {
        id: 1,
        heading: "Kitchen Renovations",
        description: "We transform your kitchen into a functional and stylish space where culinary dreams come true.",
        imgUrl: "/assets/servicesSection/services-kitchen.png",
    },
    {
        id: 2,
        heading: "Bathroom Remodeling",
        description: "Upgrade your daily routine with a renovated bathroom that blends functionality with sophistication.",
        imgUrl: "/assets/servicesSection/services-bath.png",
    },
    {
        id: 3,
        heading: "Basement Renovation",
        description: "We innovatively and creatively revamp underutilized spaces into vibrant, functional rooms of practical elegance.",
        imgUrl: "/assets/servicesSection/services-basement.png",
    },
];

export const pricesSectionCards = [
    {
        id: 1,
        triggerText: "3-Piece Bathroom",
        heading: "Included in 3-Piece Bathroom Renovation:",
        bulletList: [
            "Plumbing adjustments and installation of tub/shower",
            "Waterproofing",
            "Tiling on walls and floor",
            "Drywall work and painting",
            "Fitting toilet, vanity, wall accessories, and trim.",
        ],
        note: "Please Note: Finish materials such as sinks, faucets, tiles, vanities, and toilets are to be supplied by you, allowing customization to match your style",
        price: "Starting from $11,900",
        btnText: "Get a Quote",
        imgUrl: "/assets/pricesSection/prices-3pc.png",
        skeletonImgUrl: "/assets/pricesSection/skeletons/prices-skeleton-3pc.png",
    },
    {
        id: 2,
        triggerText: "4-Piece Bathroom",
        heading: "Included in 4-Piece Bathroom Renovation:",
        bulletList: [
            "Waterproofing",
            "Installation of free-standing tub and faucet.",
            "Tiling on walls and floor",
            "Installation of acrylic shower base",
            "Drywall work and painting",
            "Fitting toilet, vanity, wall accessories, and trim.",
        ],
        note: "Please Note: Finish materials such as sinks, faucets, tiles, vanities, and toilets are to be supplied by you, allowing customization to match your style",
        price: "Starting from $14,900",
        btnText: "Get a Quote",
        imgUrl: "/assets/pricesSection/prices-4pc.png",
        skeletonImgUrl: "/assets/pricesSection/skeletons/prices-skeleton-4pc.png",
    },
    {
        id: 3,
        triggerText: "Powder Room",
        heading: "Included in Powder Room Renovation:",
        bulletList: [
            "Plumbing adjustments and installation of sink/toilet",
            "Waterproofing",
            "Precision tiling for floor",
            "Demolition and disposal",
            "Seamless installation of essentials",
        ],
        note: "Please Note: Finish materials such as sinks, faucets, tiles, vanities, and toilets are to be supplied by you, allowing customization to match your style",
        price: "Starting from $5,900",
        btnText: "Get a Quote",
        imgUrl: "/assets/pricesSection/prices-powder.png",
        skeletonImgUrl: "/assets/pricesSection/skeletons/prices-skeleton-powder.png",
    },
    {
        id: 4,
        triggerText: "Tub to Shower",
        heading: "Included in Tub to Shower Renovation:",
        bulletList: [
            "Plumbing adjustments and installation of shower",
            "Waterproofing",
            "Precision tiling for walls and floor",
            "Demolition and disposal",
            "Seamless installation of essentials",
        ],
        note: "Please Note: Finish materials such as sinks, faucets, tiles, vanities, and toilets are to be supplied by you, allowing customization to match your style",
        price: "Starting from $5,900",
        btnText: "Get a Quote",
        imgUrl: "/assets/pricesSection/prices-tubToShower.png",
        skeletonImgUrl: "/assets/pricesSection/skeletons/prices-skeleton-tubToShower.png",
    },
    {
        id: 5,
        triggerText: "Custom Shower",
        heading: "Included in Custom Shower Renovation:",
        bulletList: [
            "Plumbing adjustments and installation of shower",
            "Waterproofing",
            "Tiling for walls and shower base floor",
            "Demolition and disposal",
            "Installation of essentials",
        ],
        note: "Please Note: Finish materials such as sinks, faucets, tiles, vanities, and toilets are to be supplied by you, allowing customization to match your style",
        price: "Starting from $7,900",
        btnText: "Get a Quote",
        imgUrl: "/assets/pricesSection/prices-customShower.png",
        skeletonImgUrl: "/assets/pricesSection/skeletons/prices-skeleton-customShower.png",
    },
    {
        id: 6,
        triggerText: "Laundry Room",
        heading: "Included in Laundry Room Renovation:",
        bulletList: [
            "Plumbing adjustments and installation of utility sink and laundry connections",
            "Waterproofing of walls near the sink and laundry area",
            "Installation of the flooring",
            "Installation of essentials",
        ],
        note: "Please Note: Finish materials such as sinks, faucets, tiles, vanities, and toilets are to be supplied by you, allowing customization to match your style",
        price: "Starting from $4,900",
        btnText: "Get a Quote",
        imgUrl: "/assets/pricesSection/prices-laundry.png",
        skeletonImgUrl: "/assets/pricesSection/skeletons/prices-skeleton-laundry.png",
    },
    {
        id: 7,
        triggerText: "Basement Bathroom",
        heading: "Included in Basement Bathroom Renovation:",
        bulletList: [
            "Plumbing adjustments and installation of tub/shower",
            "Waterproofing",
            "Tiling on walls and floor",
            "Drywall work and painting",
            "Fitting toilet, vanity, wall accessories, and trim.",
        ],
        note: "Please Note: Finish materials such as sinks, faucets, tiles, vanities, and toilets are to be supplied by you, allowing customization to match your style",
        price: "Starting from $18,900",
        btnText: "Get a Quote",
        imgUrl: "/assets/pricesSection/prices-basementShower.png",
        skeletonImgUrl: "/assets/pricesSection/skeletons/prices-skeleton-basementShower.png",
    },
    {
        id: 8,
        triggerText: "Full Basement and Bathroom",
        heading: "Included in Full Basement and Bathroom Renovation:",
        bulletList: [
            "Non-Structural enhancements and repairs",
            "Insulation and moisture barrier installation",
            "Drywall installation and painting",
            "Flooring installation",
            "Electrical and lighting upgrades ",
            "Customized storage solutions",
            "Installation of 3-piece bathroom",
        ],
        note: "Please Note: Finish materials such as sinks, faucets, tiles, vanities, and toilets are to be supplied by you, allowing customization to match your style",
        price: "Starting from $39,900",
        btnText: "Get a Quote",
        imgUrl: "/assets/pricesSection/prices-basement.png",
        skeletonImgUrl: "/assets/pricesSection/skeletons/prices-skeleton-basement.png",
    },
    {
        id: 9,
        triggerText: "Kitchen Refacing",
        heading: "Included in Kitchen Refacing:",
        bulletList: [
            "Fast Kitchen Transformation",
            "No Hidden Costs",
            "Variety of Styles",
            "Customizable Accessories",
            "Less Mess, Less Expense",
        ],
        note: "Please Note: Finish materials such as sinks, faucets and other fixtures should be provided by you, enabling customization to match your preferred style.",
        price: "Starting from $15,900",
        btnText: "Get a Quote",
        imgUrl: "/assets/pricesSection/prices-kitchen.png",
        skeletonImgUrl: "/assets/pricesSection/skeletons/prices-skeleton-kitchen.png",
    },
];

export const gallerySectionCards = [
    {
        id: 1,
        title: "Bathroom Renovations",
        imgUrl: "/assets/gallerySection/gallery-1.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-1.png",
    },
    {
        id: 2,
        title: "Kitchen Renovations",
        imgUrl: "/assets/gallerySection/gallery-2.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-2.png",
    },
    {
        id: 3,
        title: "Bathroom Renovations",
        imgUrl: "/assets/gallerySection/gallery-3.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-3.png",
    },
    {
        id: 4,
        title: "Bathroom Renovations",
        imgUrl: "/assets/gallerySection/gallery-4.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-4.png",
    },
    {
        id: 5,
        title: "Bathroom Renovations",
        imgUrl: "/assets/gallerySection/gallery-5.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-5.png",
    },
    {
        id: 6,
        title: "Bathroom Renovations",
        imgUrl: "/assets/gallerySection/gallery-6.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-6.png",
    },
    {
        id: 7,
        title: "Kitchen Renovations",
        imgUrl: "/assets/gallerySection/gallery-7.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-7.png",
    },
    {
        id: 8,
        title: "Bathroom Renovations",
        imgUrl: "/assets/gallerySection/gallery-8.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-8.png",
    },
    {
        id: 9,
        title: "Kitchen Renovations",
        imgUrl: "/assets/gallerySection/gallery-9.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-9.png",
    },
    {
        id: 10,
        title: "Bathroom Renovations",
        imgUrl: "/assets/gallerySection/gallery-10.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-10.png",
    },
    {
        id: 11,
        title: "Basement Renovations",
        imgUrl: "/assets/gallerySection/gallery-11.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-11.png",
    },
    {
        id: 12,
        title: "Bathroom Renovations",
        imgUrl: "/assets/gallerySection/gallery-12.png",
        skeletonImgUrl: "/assets/gallerySection/skeleton/gallery-skeleton-12.png",
    },


];